language: java
sudo: false
before_script: 
  - cd RailwayTicketOffice
  - psql -c 'create database railwayticketoffice;' -U postgres
   - psql -c 'create database railwayticketofficetest;' -U postgres
script:
  - mvn clean verify
  - mvn checkstyle:checkstyle
  - mvn spotbugs:spotbugs
after_success:
  - mvn clean test jacoco:report coveralls:report